from pathlib import Path
import csv, json
import pandas as pd
from docx import Document
from docx.shared import Inches, Pt
from docx.enum.text import WD_ALIGN_PARAGRAPH
from docx.enum.table import WD_TABLE_ALIGNMENT
from docx.oxml import OxmlElement
from docx.oxml.ns import qn

ROOT = Path(r'C:\Users\welki\Desktop\midterm')
OUT = ROOT / 'outputs'
ASSETS = OUT / 'visualizations'
REPORT = ROOT / 'HW2_report_updated.docx'

def read_csv(path):
    with open(path, newline='', encoding='utf-8-sig') as f:
        return list(csv.DictReader(f))

def fmt(x):
    try:
        return f'{float(x):.4f}'
    except Exception:
        return str(x)

def shade(cell, fill='D9EAF7'):
    tc_pr = cell._tc.get_or_add_tcPr()
    shd = OxmlElement('w:shd')
    shd.set(qn('w:fill'), fill)
    tc_pr.append(shd)

def add_table(doc, headers, rows):
    table = doc.add_table(rows=1, cols=len(headers))
    table.style = 'Table Grid'
    table.alignment = WD_TABLE_ALIGNMENT.CENTER
    for i, h in enumerate(headers):
        c = table.rows[0].cells[i]
        c.text = str(h)
        shade(c)
        for p in c.paragraphs:
            for r in p.runs:
                r.bold = True
    for row in rows:
        cells = table.add_row().cells
        for i, v in enumerate(row):
            cells[i].text = str(v)
    return table

def add_picture(doc, path, width=5.7, caption=None):
    path = Path(path)
    if not path.exists():
        return
    p = doc.add_paragraph()
    p.alignment = WD_ALIGN_PARAGRAPH.CENTER
    p.add_run().add_picture(str(path), width=Inches(width))
    if caption:
        c = doc.add_paragraph(caption)
        c.alignment = WD_ALIGN_PARAGRAPH.CENTER

def set_fonts(doc):
    for name in ['Normal', 'Heading 1', 'Heading 2', 'Heading 3']:
        style = doc.styles[name]
        style.font.name = '宋体'
        style._element.rPr.rFonts.set(qn('w:eastAsia'), '宋体')
    doc.styles['Normal'].font.size = Pt(10.5)

def infer_task1_meta(exp_name):
    arch = exp_name
    attention = 'none'
    pretrained = 'True'
    if exp_name == 'resnet18_random':
        arch = 'resnet18'; pretrained = 'False'
    elif exp_name.endswith('_se'):
        arch = exp_name.replace('_pretrained_se', '')
        attention = 'se'
    elif exp_name.endswith('_cbam'):
        arch = exp_name.replace('_pretrained_cbam', '')
        attention = 'cbam'
    elif exp_name.endswith('_pretrained'):
        arch = exp_name.replace('_pretrained', '')
    return arch, pretrained, attention

def load_task1_rows():
    rows = []
    seen = set()
    summary = OUT / 'task1' / 'ablation_summary.csv'
    if summary.exists():
        for r in read_csv(summary):
            rows.append(r); seen.add(r['exp_name'])
    for p in sorted((OUT / 'task1').glob('*_history.json')):
        exp = p.stem.replace('_history', '')
        if exp in seen:
            continue
        history = json.load(open(p, encoding='utf-8'))
        best = max(history, key=lambda x: x.get('val_acc', 0))
        arch, pretrained, attention = infer_task1_meta(exp)
        rows.append({
            'exp_name': exp,
            'arch': arch,
            'pretrained': pretrained,
            'attention': attention,
            'best_val_acc': best.get('val_acc', ''),
            'test_acc': '',
        })
    return rows

# Ensure visualizations are current if script exists.
# This report consumes outputs/visualizations generated by visualize_results.py.

task1_rows = load_task1_rows()
task3_rows = read_csv(OUT / 'task3' / 'loss_comparison.csv')
pc_ce = read_csv(OUT / 'task3' / 'per_class_iou_ce.csv')
pc_dice = read_csv(OUT / 'task3' / 'per_class_iou_dice.csv')
pc_combined = read_csv(OUT / 'task3' / 'per_class_iou_combined.csv')
tracking = json.load(open(OUT / 'task2' / 'tracking_summary.json', encoding='utf-8'))
yolo_last = pd.read_csv(OUT / 'task2' / 'vehicle_finetune' / 'results.csv').iloc[-1]

# Histories for best epoch summaries
task3_hist = {}
for p in sorted((OUT / 'task3').glob('history_*.json')):
    mode = p.stem.replace('history_', '')
    hist = json.load(open(p, encoding='utf-8'))
    task3_hist[mode] = max(hist, key=lambda x: x.get('val_mIoU', 0))

doc = Document()
set_fonts(doc)

title = doc.add_paragraph()
title.alignment = WD_ALIGN_PARAGRAPH.CENTER
run = title.add_run('HW2 深度学习与空间智能实验报告（更新版）')
run.bold = True
run.font.size = Pt(18)
subtitle = doc.add_paragraph()
subtitle.alignment = WD_ALIGN_PARAGRAPH.CENTER
subtitle.add_run('任务一：花卉分类 | 任务二：车辆检测跟踪与计数 | 任务三：U-Net 语义分割')

doc.add_paragraph('本报告根据 HW2_深度学习与空间智能.pdf 的要求，结合最新 outputs 目录中的实验结果，整理三个任务的实验设计、关键结果、可视化图表和分析结论。文档使用中文字体生成，避免中文乱码。')

doc.add_heading('1. 实验环境与结果文件', level=1)
add_table(doc, ['项目', '内容'], [
    ['主要框架', 'PyTorch、torchvision、Ultralytics YOLOv8、OpenCV'],
    ['任务一数据集', 'Oxford 102 Category Flower Dataset'],
    ['任务二数据集', 'Road Vehicle Images Dataset 与交通视频 test_video.mp4'],
    ['任务三数据集', 'Stanford Background Dataset，使用 labels_raw/*.regions.txt 作为 8 类语义标签'],
    ['结果目录', 'outputs/task1、outputs/task2、outputs/task3、outputs/visualizations'],
])

doc.add_paragraph('本次更新后的 outputs 中，任务一除原始 ResNet 消融外，还包含 EfficientNet-B0、ConvNeXt-Tiny、Swin-T 的训练历史；任务三最新结果中 CE + Dice 组合损失取得最高 mIoU。')

# Task 1
doc.add_heading('2. 任务一：ImageNet 预训练 CNN 花卉分类', level=1)
doc.add_paragraph('任务要求是在 102 Category Flower Dataset 上建立 ResNet-18 或 ResNet-34 baseline，比较 ImageNet 预训练与从零训练，并加入 SE-block 或 CBAM 注意力模块进行性能比较。改进实验进一步加入 EfficientNet-B0、ConvNeXt-Tiny 和 Swin-T 作为更强 backbone。')
doc.add_heading('2.1 方法', level=2)
doc.add_paragraph('模型将分类头替换为 102 类输出。预训练实验加载 ImageNet 权重，随机初始化实验用于验证预训练贡献；SE 和 CBAM 用于注意力模块消融。训练策略包括 AdamW、差异学习率、Label Smoothing、RandAugment、MixUp/CutMix、Warmup + Cosine 学习率调度。')
doc.add_heading('2.2 结果', level=2)
rows = []
for r in task1_rows:
    rows.append([
        r['exp_name'], r['arch'], r.get('pretrained', ''), r.get('attention', ''),
        fmt(r.get('best_val_acc', '')), fmt(r.get('test_acc', '')) if r.get('test_acc') != '' else '未记录'
    ])
add_table(doc, ['实验', '模型', '预训练', '注意力', 'Best Val Acc', 'Test Acc'], rows)
add_picture(doc, ASSETS / 'task1_test_accuracy.png', caption='图 1 任务一测试集准确率对比')
add_picture(doc, ASSETS / 'task1_val_accuracy_curves.png', caption='图 2 任务一验证准确率曲线')
doc.add_heading('2.3 分析', level=2)
summary_rows = [r for r in task1_rows if r.get('test_acc') not in ['', None]]
if summary_rows:
    best = max(summary_rows, key=lambda r: float(r['test_acc']))
    random_row = next((r for r in summary_rows if r['exp_name'] == 'resnet18_random'), None)
    base_row = next((r for r in summary_rows if r['exp_name'] == 'resnet18_pretrained'), None)
    if base_row and random_row:
        doc.add_paragraph(f'预训练效果明显：ResNet-18 预训练测试准确率为 {fmt(base_row["test_acc"])}，随机初始化为 {fmt(random_row["test_acc"])}。这说明 ImageNet 预训练特征能显著提升花卉小样本分类性能。')
    doc.add_paragraph(f'原始消融结果中，最优测试准确率来自 {best["exp_name"]}，Test Acc = {fmt(best["test_acc"])}。新增 backbone 的验证曲线已纳入图 2，可用于报告中比较更强结构的收敛趋势。')

# Task 2
doc.add_heading('3. 任务二：YOLOv8 车辆检测、跟踪与跨线计数', level=1)
doc.add_paragraph('任务要求使用 Road Vehicle Images Dataset 训练 YOLOv8，随后对 10-30 秒车辆视频输出 Bounding Box 和 Tracking ID，分析遮挡/ID 变化帧，并统计跨越虚拟线的目标数量。')
doc.add_heading('3.1 方法', level=2)
doc.add_paragraph('检测部分使用 YOLOv8 微调车辆类别；视频阶段调用 YOLOv8 track 接口并使用 ByteTrack 维护 Tracking ID。计数通过检测框中心点相对虚拟线的叉积符号变化判断是否过线，并用 crossed_ids 避免重复计数。遮挡事件通过框间 IoU 和 ID 重现间隔触发保存，并设置 event cooldown 防止连续帧重复保存。')
doc.add_heading('3.2 检测结果', level=2)
add_table(doc, ['指标', '结果'], [
    ['Precision(B)', fmt(yolo_last['metrics/precision(B)'])],
    ['Recall(B)', fmt(yolo_last['metrics/recall(B)'])],
    ['mAP50(B)', fmt(yolo_last['metrics/mAP50(B)'])],
    ['mAP50-95(B)', fmt(yolo_last['metrics/mAP50-95(B)'])],
    ['训练 epoch', int(yolo_last['epoch'])],
])
add_picture(doc, ASSETS / 'task2_yolo_map_curve.png', caption='图 3 YOLOv8 验证集 mAP 曲线')
add_picture(doc, ASSETS / 'task2_yolo_loss_curve.png', caption='图 4 YOLOv8 训练与验证 loss 曲线')
add_picture(doc, OUT / 'task2' / 'vehicle_finetune' / 'confusion_matrix_normalized.png', width=5.0, caption='图 5 归一化混淆矩阵')
doc.add_heading('3.3 跟踪计数结果', level=2)
add_table(doc, ['项目', '结果'], [
    ['输出视频', 'outputs/task2/tracked_output.mp4'],
    ['虚拟线', f"{tracking['line_pt1']} -> {tracking['line_pt2']}"],
    ['跨线目标总数', tracking['total_cross_count']],
    ['保存遮挡事件数', tracking['occlusion_events_saved']],
    ['事件冷却间隔', f"{tracking.get('event_cooldown_frames', 0)} frames"],
    ['跨线 Tracking ID', ', '.join(map(str, tracking['crossed_ids']))],
])
add_picture(doc, ASSETS / 'task2_tracking_summary.png', caption='图 6 跟踪计数摘要')
add_picture(doc, ASSETS / 'task2_tracked_midframe.jpg', width=4.8, caption='图 7 跟踪输出视频中间帧示例')
add_picture(doc, ASSETS / 'task2_occlusion_montage.jpg', width=5.3, caption='图 8 遮挡或密集目标事件帧拼图')
doc.add_heading('3.4 视频分析步骤', level=2)
for s in [
    '打开 outputs/task2/tracked_output.mp4，检查检测框、类别、置信度和 Tracking ID 是否显示完整。',
    '观察虚拟线附近车辆中心点轨迹，确认车辆跨线时 Count 增加，同一 ID 不重复计数。',
    '查看 outputs/task2/occlusion_frames/event_00 至 event_03 中的连续帧，分析车辆遮挡前后 ID 是否保持一致。',
    '若遮挡前后同一车辆 ID 不变，可说明 ByteTrack 保持了目标身份；若 ID 跳变，则记录为潜在 ID switch。',
    '结合 tracking_summary.json 汇总 total_cross_count、crossed_ids 和 occlusion_events_saved。',
]:
    doc.add_paragraph(s)
doc.add_heading('3.5 分析', level=2)
doc.add_paragraph(f'检测模型最终 mAP50 为 {fmt(yolo_last["metrics/mAP50(B)"])}，mAP50-95 为 {fmt(yolo_last["metrics/mAP50-95(B)"])}。视频中最终统计到 {tracking["total_cross_count"]} 个跨线目标，保存 {tracking["occlusion_events_saved"]} 组遮挡事件。计数逻辑基于 Tracking ID 去重，因此可以减少同一车辆在线附近抖动造成的重复计数。')

# Task 3
doc.add_heading('4. 任务三：从零实现 U-Net 与 Loss 对比', level=1)
doc.add_paragraph('任务要求从零搭建 U-Net，包括下采样、上采样和 Skip Connection，在 Stanford Background Dataset 上训练，并比较 Cross-Entropy Loss、Dice Loss、CE + Dice Loss 的 mIoU。改进代码中还支持 Attention U-Net、类别重加权和 CE/Dice 权重搜索。')
doc.add_heading('4.1 方法', level=2)
doc.add_paragraph('U-Net 由四层 Encoder、Bottleneck 和四层 Decoder 构成。Encoder 使用 ConvBlock + MaxPool，Decoder 使用反卷积上采样，并与对应 Encoder 特征通过 Skip Connection 拼接。输出层为 1x1 卷积，预测 8 类语义分割图。训练中使用同步水平翻转和 ColorJitter，并输出平均 mIoU 与逐类 IoU。')
doc.add_heading('4.2 Loss 对比结果', level=2)
add_table(doc, ['Loss', 'Best Val mIoU', '最佳 Epoch'], [
    [r['loss_mode'], fmt(r['best_val_mIoU']), task3_hist.get(r['loss_mode'], {}).get('epoch', '')]
    for r in task3_rows
])
add_picture(doc, ASSETS / 'task3_loss_comparison.png', caption='图 9 不同 Loss 的 mIoU 对比')
add_picture(doc, ASSETS / 'task3_val_miou_curves.png', caption='图 10 任务三验证 mIoU 曲线')
doc.add_heading('4.3 逐类 IoU', level=2)
add_table(doc, ['Class ID', 'Class Name', 'CE', 'Dice', 'Combined'], [
    [row['class_id'], row['class_name'], fmt(row['iou']), fmt(pc_dice[i]['iou']), fmt(pc_combined[i]['iou'])]
    for i, row in enumerate(pc_ce)
])
add_picture(doc, ASSETS / 'task3_per_class_iou_all_losses.png', caption='图 11 三种 Loss 下逐类 IoU 对比')
doc.add_heading('4.4 分析', level=2)
best_t3 = max(task3_rows, key=lambda r: float(r['best_val_mIoU']))
doc.add_paragraph(f'最新任务三结果中，{best_t3["loss_mode"]} 的 best val mIoU 最高，为 {fmt(best_t3["best_val_mIoU"])}。这表明 CE 与 Dice 的组合在当前数据上更好地兼顾了像素级分类监督和区域重叠优化。Dice Loss 单独训练低于组合损失，说明单独依赖区域重叠目标在多类复杂场景中不够稳定。')
doc.add_paragraph('逐类 IoU 可用于分析不同语义类别的难度。通常 sky、road、building 等大面积或边界清晰类别表现较好，而 mountain 等样本较少或外观变化大的类别更难。后续可以结合 class-weighted loss、Attention U-Net 或更多 CE/Dice 权重组合继续改进。')

# Summary
doc.add_heading('5. 总结与改进方向', level=1)
doc.add_paragraph('三个任务分别覆盖图像级分类、目标级检测跟踪和像素级语义分割。任务一验证了预训练、注意力机制和更强 backbone 的作用；任务二实现了车辆检测、Tracking ID、遮挡分析和跨线计数；任务三完成了 U-Net 从零实现、损失函数对比和逐类 IoU 分析。')
add_table(doc, ['任务', '已完成内容', '可继续改进方向'], [
    ['任务一', 'ResNet 预训练/随机初始化消融，SE/CBAM 对比，EfficientNet/ConvNeXt/Swin 扩展，Accuracy 曲线', '继续系统搜索增强策略、学习率和更强 backbone'],
    ['任务二', 'YOLOv8 微调、ByteTrack 跟踪、虚拟线计数、遮挡事件保存、视频帧可视化', '尝试 YOLOv8s/m，提高小类别样本量，人工优化计数线位置'],
    ['任务三', 'U-Net 从零实现，CE/Dice/Combined Loss 对比，逐类 IoU 分析，支持 Attention U-Net 和类别重加权', '继续搜索 CE/Dice 权重、类别权重策略和更强分割结构'],
])
doc.add_paragraph('附：所有训练曲线、统计表、输出视频、遮挡帧和可视化图片均保存在 outputs 目录，可直接用于报告或 PPT。')

doc.save(REPORT)
print(REPORT)
